# reusable-review.yml (디버깅용 - SSH 조건 모두 제거)

name: Reusable Code Review
on:
  workflow_call:
    inputs:
      repository:
        description: 'Target repository'
        required: true
        type: string
      pr-number:
        description: 'Pull request number'
        required: true
        type: number
      base-sha:
        description: 'Base SHA'
        required: true
        type: string
      head-sha:
        description: 'Head SHA'
        required: true
        type: string
    secrets:
      LLM_API_URL:
        required: false

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Debug - Print inputs
      run: |
        echo "=== 디버깅 정보 ==="
        echo "Repository: ${{ inputs.repository }}"
        echo "PR Number: ${{ inputs.pr-number }}"
        echo "Base SHA: ${{ inputs.base-sha }}"
        echo "Head SHA: ${{ inputs.head-sha }}"
        echo "API URL: ${{ secrets.LLM_API_URL }}"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code review (without SSH)
      env:
        GITHUB_TOKEN: ${{ github.token }}
        LLM_API_URL: ${{ secrets.LLM_API_URL || 'http://localhost:11434' }}
      run: |
        echo "=== 코드 리뷰 실행 (SSH 없이) ==="
        echo "API URL: ${{ env.LLM_API_URL }}"
        
        # 우선 로컬 LLM 없이 테스트
        echo "워크플로우가 여기까지 정상 실행됨!"
        
        # 실제 코드리뷰는 나중에 활성화
        # python src/main.py \
        #   --repo ${{ inputs.repository }} \
        #   --pr-number ${{ inputs.pr-number }} \
        #   --base-sha ${{ inputs.base-sha }} \
        #   --head-sha ${{ inputs.head-sha }} \
        #   --api-url ${{ env.LLM_API_URL }}