# self-review.yml (디버깅용 - 최소한의 설정)

name: Self Code Review (Debug)
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:  # 수동 트리거 추가

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    uses: ./.github/workflows/reusable-review.yml
    with:
      repository: ${{ github.repository }}
      pr-number: ${{ github.event.pull_request.number || 1 }}
      base-sha: ${{ github.event.pull_request.base.sha || 'main' }}
      head-sha: ${{ github.event.pull_request.head.sha || 'HEAD' }}
    secrets:
      LLM_API_URL: ${{ secrets.LLM_API_URL }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      LLM_SERVER_HOST: ${{ secrets.LLM_SERVER_HOST }}
      LLM_SERVER_PORT: ${{ secrets.LLM_SERVER_PORT }}
      LLM_SERVER_USER: ${{ secrets.LLM_SERVER_USER }}